name: Nix environment

on:
  push:
    paths:
      - flake.nix
      - shell.nix
      - flake.lock
    branches:
      - master
  pull_request:
    paths:
      - flake.nix
      - shell.nix
      - flake.lock
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: cachix/install-nix-action@v15
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: saber
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check flake
        run: nix flake check -v --show-trace --no-update-lock-file
      - run: nix develop -c echo success
